service: auth-server

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 60 

functions:
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
  getRefreshToken:
    handler: handler.getRefreshToken
    events: 
      -http:
          path: api/token/{code}
          method: get
